print('\nDissecando uma variável!')
a = input('\nDigite algo: ')
print('\nO tipo primitivo desse valor é ', type(a))
print('\nSó tem espaços? ', a.isspace())
print('\nÉ um numeral?: ', a.isnumeric())
print('\nÉ alfabetico?: ', a.isalpha())
print('\nEstá em maiúscula?: ', a.isupper())
print('\nEstá em minúscula?: ', a.islower())
print('\nEstá capitalizada?: ', a.istitle())
